#!/bin/bash

GPIO=/usr/bin/gpio


PSU_PIN_BCM=21
LASER_PIN_BCM=20
GRBL_PIN_BCM=27

activate()
{
  sudo $GPIO -g write $1 0
}

deactivate()
{
  sudo $GPIO -g write $1 1
}

toggle_power()
{
  local DIGITAL=$(sudo $GPIO -g read $1)
  if [ $DIGITAL = 1 ]; then
    activate $1
  elif [ $DIGITAL = 0 ]; then
    deactivate $1
  fi
}

grbl_reset()
{
  sudo $GPIO -g write $GRBL_PIN_BCM 0
  sleep 0.5
  sudo $GPIO -g write $GRBL_PIN_BCM 1
}

get_power_status()
{
  local OUT=""
  local DIGITAL=$(sudo $GPIO -g read $1)
  if [ $DIGITAL = 1 ]; then OUT="off"; fi
  if [ $DIGITAL = 0 ]; then OUT="on"; fi
  echo $OUT
}



#LASER=$(get_power_status $LASER_PIN_BCM)
#PSU=$(get_power_status $PSU_PIN_BCM)

printf "+------------------------------------------------------------------------------+\n"
printf "| This program will allow you to change the state of the laser and PSU, and    |\n"
printf "| reset the GRBL board if you really need to.                                  |\n"
printf "+------------------------------------------------------------------------------+\n"
printf "| Press the number of the device you wish to toggle.                           |\n"
printf "+------------------------------------------------------------------------------+\n"

LASER=$(get_power_status $LASER_PIN_BCM)
PSU=$(get_power_status $PSU_PIN_BCM)


while true; do
  if [[ "$LASER" = "off" ]] && [[ "$PSU" = "off" ]]; then
    printf "| Current Values: \t Laser: \e[100m%s\e[0m \t\t PSU: \e[100m%s\e[0m \t GRBL\t       |\n" "$LASER" "$PSU"

  elif [[ "$LASER" = "on" ]] && [[ "$PSU" = "off" ]]; then
    printf "| Current Values: \t Laser: \e[41m%s\e[0m \t\t PSU: \e[100m%s\e[0m \t GRBL\t       |\n" "$LASER" "$PSU"

  elif [[ "$LASER" = "off" ]] && [[ "$PSU" = "on" ]]; then
    printf "| Current Values: \t Laser: \e[100m%s\e[0m \t\t PSU: \e[41m%s\e[0m \t GRBL\t       |\n" "$LASER" "$PSU"

  elif [[ "$LASER" = "on" ]] && [[ "$PSU" = "on" ]]; then
    printf "| Current Values: \t Laser: \e[41m%s\e[0m \t\t PSU: \e[41m%s\e[0m \t GRBL\t       |\n" "$LASER" "$PSU"

  else
    printf "| Current Values: \t Laser: \e[43m%s\e[0m \t\t PSU: \e[43m%s\e[0m \t GRBL\t        |\n" "$LASER" "$PSU"
  fi

  printf "| \t\t\t (1) \t\t\t (2) \t\t (3) \t       |\n"
  printf "+--------------------------------(e) to exit-----------------------------------+\n"
  
  read -n 1 -r -s DEVICE
  
  if [ $DEVICE = 1 ]; then
    toggle_power $LASER_PIN_BCM
    LASER=$(get_power_status $LASER_PIN_BCM)
    printf "\r\e[3A\e[2K"

  elif [ $DEVICE = 2 ]; then
    toggle_power $PSU_PIN_BCM
    PSU=$(get_power_status $PSU_PIN_BCM)
    printf "\r\e[3A\e[2K"
  
  elif [ $DEVICE = 3 ]; then
    grbl_reset
    printf "GRBL reset"
    sleep 1
    printf "\e[2K\r\e[3A\e[2K"

  elif [ "$DEVICE" = "e" ]; then
    deactivate $LASER_PIN_BCM
    deactivate $PSU_PIN_BCM
    exit 0
  
  else
    printf "Not valid option"
    sleep 1
    printf "\e[2K\r\e[3A\e[2K"
  fi
done
