#!/bin/bash -e

NFC_LIST=$(which nfc-list)
MKPASSWD=$(which mkpasswd)

printf "The output of the next command should resemble something like the following:\n"

printf "+--------------------------------------------------\n"
printf "nfc-list uses libnfc 1.7.1\nNFC device: pn532_spi:/dev/spidev0.0 opened\n1 ISO14443A passive target(s) found:\nISO/IEC 14443A (106 kbps) target:\n    ATQA (SENS_RES): 00  04  \n       UID (NFCID1): \e[32ma2  53  c3  59\e[0m  \n      SAK (SEL_RES): 08  \n"
printf "+--------------------------------------------------\n"

printf "Where the green text is the ID of the NFC tag\n"
printf "(your text will not be green, but will be in the same location)\n"

sleep 1

printf "Scanning for an NFC tag now...\n"

ISTAG=""
while [[ "$ISTAG" != "y" ]]; do
  TAG=""
  while [[ "$TAG" != *"NFCID1"* ]]; do
    TAG=$( $NFC_LIST -t 1 )
  done
  printf "\n\nIs this your tag?\n\n%s\n\n" "$TAG"
  read -n 1 -r -p "[y/N]? " ISTAG
done

printf "\nLet's continue then!\n%s\n\n" "$TAG"

TARGET_NFC=$(echo $TAG | grep -Eo '\(NFCID1\):(\s(\w|\d){2}){4}' | cut -d":" -f2 | sed -e 's/\s//g')

printf "Here's the ID that'll be encrypted: %s\n" "$TARGET_NFC"

ENC_NFC=$(mkpasswd -S RC $TARGET_NFC)

printf "The encrypted DES hash: %s\n" "$ENC_NFC"


TEST_HASH="RCVYRpjhwjgOU"
if [[ $ENC_NFC = $TEST_HASH ]]; then
  printf "It matches! %s == %s\n" "$ENC_NFC" "$TEST_HASH"
else
  printf "No match: %s != %s\n" "$ENC_NFC" "$TEST_HASH"
fi
